<?php
/**
 * @var Template $block
 * @var Escaper $escaper
 * @var OrderUpload $viewModel
 */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Oporteo\OrderUpload\ViewModel\OrderUpload;

$viewModel = $block->getData('view_model');
$widgetInitParams = (array) $block->getData('widget_init_params');

?>

<div class="order-upload"
     data-mage-init='<?= $escaper->escapeHtmlAttr($viewModel->getWidgetInitConfig($widgetInitParams)) ?>'>
    <?= /** @noEscape */ $block->getChildHtml() ?>
</div>
