<?php
/**
 * @var Template $block
 * @var Escaper $escaper
 */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

$isCurrent = $block->getRequest()->getFullActionName() === 'orderupload_index_index';

?>

<li class="link orderupload-link<?= $isCurrent ? ' current' : '' ?>">
    <a href="<?= $escaper->escapeUrl($block->getUrl('orderupload')) ?>"
       <?= $isCurrent ? 'aria-current="page"' : '' ?>>
        <?= $escaper->escapeHtml(__('Order Upload')) ?>
    </a>
</li>
