<?php
/** @var Oporteo\Csvorderupload\Block\Index\Index $block */
?>
<h2><?= $block->escapeHtml(__('Order Upload')) ?></h2>
<p><?= $block->escapeHtml(
        __(
            'Bulk ordering mode simple! Download our sample template below, fill in the order
    details and upload by selecting the file or drag and dropping into the box below. All your products will be
    automatically added to your cart. Easy!'
        )
    ); ?>
</p>
<div class="csvupload">
    <div id="notifications" class="collapsibleContainer"></div>
    <div id="loader" class="loader"></div>
    <form action="<?= $block->escapeUrl($block->getUrl('orderupload/index/fileupload')) ?>" id="myform" class="">
        <div id="dropbox" class="dropbox">
            <span>
                <?= $block->escapeHtml(__('Drag and drop your CSV file or just click here to choose')) ?>
            </span>
        </div>
        <input name="file" type="file" id="file" class="file" accept=".csv"/>
    </form>
</div>
<div class="btn-group">
    <a onclick="jQuery('#file').click(); jQuery(this).text('<?= $block->escapeHtml(__('Upload another Order')) ?>')"
       class="button action primary">
        <?= $block->escapeHtml(__('Upload Order')) ?>
    </a>
    <?php if ($block->getConfig('oporteo/general/plof')) : ?>
        <a href="<?= $block->escapeUrl($block->getUrl('orderupload/csv/priceList')) ?>"
           class="button action primary">
            <?= $block->escapeHtml(__('Get Price List File')) ?>
        </a>
    <?php endif; ?>
    <a href="<?= $block->escapeUrl($block->getUrl('orderupload/csv/template')) ?>"
       class="button action primary">
        <?= $block->escapeHtml(__('Get Template File')) ?>
    </a>
    <a href="<?= $block->escapeUrl($block->getUrl('orderupload/index/emptycart')) ?>"
       id="emptycart" class="button action primary emptycart
        <?= $block->escapeHtmlAttr(($block->isEmptyCart()) ? ' btn-no-display' : '') ?>">
        <?= $block->escapeHtml(__('Empty Cart')) ?>
    </a>
    <a href="<?php echo $block->escapeUrl($block->getUrl('checkout/cart/')); ?>" id="checkout_btn"
       class="button action primary checkout_btn
        <?= $block->escapeHtmlAttr(($block->isEmptyCart()) ? ' btn-no-display' : '') ?>">
        <?= $block->escapeHtml(__('Checkout')) ?>
    </a>
</div>
